<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class LocUpazilasTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        Schema::disableForeignKeyConstraints();

        DB::table('loc_upazilas')->truncate();


        DB::table('loc_upazilas')->insert(array(
            array('id' => '1','loc_division_id' => '4','loc_district_id' => '35','title_en' => 'BAGERHAT SADAR','title' => 'বাগেরহাট সদর','is_sadar_upazila' => '1','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '2','loc_division_id' => '4','loc_district_id' => '35','title_en' => 'CHITALMARI','title' => 'চিতলমারী','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '3','loc_division_id' => '4','loc_district_id' => '35','title_en' => 'FAKIRHAT','title' => 'ফকিরহাট','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '4','loc_division_id' => '4','loc_district_id' => '35','title_en' => 'KACHUA','title' => 'কচুয়া','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '5','loc_division_id' => '4','loc_district_id' => '35','title_en' => 'MOLLAHAT','title' => 'মোল্লাহাট','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '6','loc_division_id' => '4','loc_district_id' => '35','title_en' => 'MONGLA','title' => 'মোংলা','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '7','loc_division_id' => '4','loc_district_id' => '35','title_en' => 'MORRELGANJ','title' => 'মোড়েলগঞ্জ','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '8','loc_division_id' => '4','loc_district_id' => '35','title_en' => 'RAMPAL','title' => 'রামপাল','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '9','loc_division_id' => '4','loc_district_id' => '35','title_en' => 'SARANKHOLA','title' => 'শরনখোলা','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '10','loc_division_id' => '2','loc_district_id' => '7','title_en' => 'ALIKADAM','title' => 'আলীকদম','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '11','loc_division_id' => '2','loc_district_id' => '7','title_en' => 'BANDARBAN SADAR','title' => 'বান্দরবন সদর','is_sadar_upazila' => '1','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '12','loc_division_id' => '2','loc_district_id' => '7','title_en' => 'LAMA','title' => 'লামা','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '13','loc_division_id' => '2','loc_district_id' => '7','title_en' => 'NAIKHONGCHHARI','title' => 'নাইক্ষ্যংছড়ি','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '14','loc_division_id' => '2','loc_district_id' => '7','title_en' => 'ROWANGCHHARI','title' => 'রোয়াংছড়ি','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '15','loc_division_id' => '2','loc_district_id' => '7','title_en' => 'RUMA','title' => 'রুমা','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '16','loc_division_id' => '2','loc_district_id' => '7','title_en' => 'THANCHI','title' => 'থানচি','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '17','loc_division_id' => '1','loc_district_id' => '1','title_en' => 'AMTALI','title' => 'আমতলী','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '18','loc_division_id' => '1','loc_district_id' => '1','title_en' => 'BAMNA','title' => 'বামনা','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '19','loc_division_id' => '1','loc_district_id' => '1','title_en' => 'BARGUNA SADAR','title' => 'বরগুনা সদর','is_sadar_upazila' => '1','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '20','loc_division_id' => '1','loc_district_id' => '1','title_en' => 'BETAGI','title' => 'বেতাগী','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '21','loc_division_id' => '1','loc_district_id' => '1','title_en' => 'PATHARGHATA','title' => 'পাথরঘাটা','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '22','loc_division_id' => '1','loc_district_id' => '2','title_en' => 'AGAILJHARA','title' => 'আগৈলঝাড়া','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '23','loc_division_id' => '1','loc_district_id' => '2','title_en' => 'BABUGANJ','title' => 'বাবুগঞ্জ','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '24','loc_division_id' => '1','loc_district_id' => '2','title_en' => 'BAKERGANJ','title' => 'বাকেরগঞ্জ','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '25','loc_division_id' => '1','loc_district_id' => '2','title_en' => 'BANARI PARA','title' => 'বানারী পাড়া','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '26','loc_division_id' => '1','loc_district_id' => '2','title_en' => 'GAURNADI','title' => 'গৌরনদী','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '27','loc_division_id' => '1','loc_district_id' => '2','title_en' => 'HIZLA','title' => 'হিজলা','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '28','loc_division_id' => '1','loc_district_id' => '2','title_en' => 'BARISAL SADAR (KOTWALI)','title' => 'বরিশাল সদর','is_sadar_upazila' => '1','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '29','loc_division_id' => '1','loc_district_id' => '2','title_en' => 'MHENDIGANJ','title' => 'মেহেন্দীগঞ্জ','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '30','loc_division_id' => '1','loc_district_id' => '2','title_en' => 'MULADI','title' => 'মুলাদী','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '31','loc_division_id' => '1','loc_district_id' => '2','title_en' => 'WAZIRPUR','title' => 'উজিরপুর','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '32','loc_division_id' => '1','loc_district_id' => '3','title_en' => 'BHOLA SADAR','title' => 'ভোলা সদর','is_sadar_upazila' => '1','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '33','loc_division_id' => '1','loc_district_id' => '3','title_en' => 'BURHANUDDIN','title' => 'বোরহানউদ্দীন','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '34','loc_division_id' => '1','loc_district_id' => '3','title_en' => 'CHAR FASSON','title' => 'চর ফ্যাশন','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '35','loc_division_id' => '1','loc_district_id' => '3','title_en' => 'DAULAT KHAN','title' => 'দৌলত খান','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '36','loc_division_id' => '1','loc_district_id' => '3','title_en' => 'LALMOHAN','title' => 'লালমোহন','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '37','loc_division_id' => '1','loc_district_id' => '3','title_en' => 'MANPURA','title' => 'মনপুরা','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '38','loc_division_id' => '1','loc_district_id' => '3','title_en' => 'TAZUMUDDIN','title' => 'তজুমদ্দিন','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '39','loc_division_id' => '5','loc_district_id' => '45','title_en' => 'ADAMDIGHI','title' => 'আদমদিঘী','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '40','loc_division_id' => '5','loc_district_id' => '45','title_en' => 'BOGRA SADAR','title' => 'বগুড়া সদর','is_sadar_upazila' => '1','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '41','loc_division_id' => '5','loc_district_id' => '45','title_en' => 'DHUNAT','title' => 'ধুনট','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '42','loc_division_id' => '5','loc_district_id' => '45','title_en' => 'DHUPCHANCHIA','title' => 'দুপচাঁচিয়া','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '43','loc_division_id' => '5','loc_district_id' => '45','title_en' => 'GABTALI','title' => 'গাবতলী','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '44','loc_division_id' => '5','loc_district_id' => '45','title_en' => 'KAHALOO','title' => 'কাহালু','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '45','loc_division_id' => '5','loc_district_id' => '45','title_en' => 'NANDIGRAM','title' => 'নন্দীগ্রাম','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '46','loc_division_id' => '5','loc_district_id' => '45','title_en' => 'SARIAKANDI','title' => 'সারিয়াকান্দি','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '47','loc_division_id' => '5','loc_district_id' => '45','title_en' => 'SHAJAHANPUR','title' => 'শাজাহানপুর','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '48','loc_division_id' => '5','loc_district_id' => '45','title_en' => 'SHERPUR','title' => 'শেরপুর','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '49','loc_division_id' => '5','loc_district_id' => '45','title_en' => 'SHIBGANJ','title' => 'শিব্‌গঞ্জ','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '50','loc_division_id' => '5','loc_district_id' => '45','title_en' => 'SONATOLA','title' => 'সোনাতলা','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '51','loc_division_id' => '2','loc_district_id' => '8','title_en' => 'AKHAURA','title' => 'আখাউড়া','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '52','loc_division_id' => '2','loc_district_id' => '8','title_en' => 'BANCHHARAMPUR','title' => 'বাঞ্ছারামপুর','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '53','loc_division_id' => '2','loc_district_id' => '8','title_en' => 'BRAHMANBARIA SADAR','title' => 'ব্রাক্ষ্মণবাড়িয়া সদর','is_sadar_upazila' => '1','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '54','loc_division_id' => '2','loc_district_id' => '8','title_en' => 'ASHUGANJ','title' => 'আশুগঞ্জ','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '55','loc_division_id' => '2','loc_district_id' => '8','title_en' => 'KASBA','title' => 'কস্‌বা','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '56','loc_division_id' => '2','loc_district_id' => '8','title_en' => 'NABINAGAR','title' => 'নবীনগর','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '57','loc_division_id' => '2','loc_district_id' => '8','title_en' => 'NASIRNAGAR','title' => 'নাসিরনগর','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '58','loc_division_id' => '2','loc_district_id' => '8','title_en' => 'SARAIL','title' => 'সরাইল','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '59','loc_division_id' => '2','loc_district_id' => '9','title_en' => 'CHANDPUR SADAR','title' => 'চাঁদপুর সদর','is_sadar_upazila' => '1','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '60','loc_division_id' => '2','loc_district_id' => '9','title_en' => 'FARIDGANJ','title' => 'ফরিদগঞ্জ','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '61','loc_division_id' => '2','loc_district_id' => '9','title_en' => 'HAIM CHAR','title' => 'হাইমচর','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '62','loc_division_id' => '2','loc_district_id' => '9','title_en' => 'HAJIGANJ','title' => 'হাজীগঞ্জ','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '63','loc_division_id' => '2','loc_district_id' => '9','title_en' => 'KACHUA','title' => 'কচুয়া','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '64','loc_division_id' => '2','loc_district_id' => '9','title_en' => 'MATLAB DAKSHIN','title' => 'মতলব দক্ষিণ','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '65','loc_division_id' => '2','loc_district_id' => '9','title_en' => 'MATLAB UTTAR','title' => 'মতলব উত্তর','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '66','loc_division_id' => '2','loc_district_id' => '9','title_en' => 'SHAHRASTI','title' => 'শাহরাস্তি','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '67','loc_division_id' => '2','loc_district_id' => '10','title_en' => 'ANOWARA','title' => 'আনোয়ারা','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '68','loc_division_id' => '2','loc_district_id' => '10','title_en' => 'BANSHKHALI','title' => 'বাঁশখালী','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '69','loc_division_id' => '2','loc_district_id' => '10','title_en' => 'BOALKHALI','title' => 'বোয়ালখালী','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '70','loc_division_id' => '2','loc_district_id' => '10','title_en' => 'CHANDANAISH','title' => 'চন্দনাইশ','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '71','loc_division_id' => '3','loc_district_id' => '31','title_en' => 'KALUKHALI','title' => 'কালুখালী','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '72','loc_division_id' => '2','loc_district_id' => '10','title_en' => 'FATIKCHHARI','title' => 'ফটিকছড়ি','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '73','loc_division_id' => '2','loc_district_id' => '10','title_en' => 'HATHAZARI','title' => 'হাটহাজারী','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '74','loc_division_id' => '2','loc_district_id' => '10','title_en' => 'LOHAGARA','title' => 'লোহাগাড়া','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '75','loc_division_id' => '2','loc_district_id' => '10','title_en' => 'MIRSHARAI','title' => 'মীরসরাই','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '76','loc_division_id' => '2','loc_district_id' => '8','title_en' => 'BIJOYNAGAR','title' => 'বিজয়নগর','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '77','loc_division_id' => '1','loc_district_id' => '5','title_en' => 'RANGABALI','title' => 'রাঙ্গাবালি','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '78','loc_division_id' => '2','loc_district_id' => '10','title_en' => 'PATIYA','title' => 'পটিয়া','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '79','loc_division_id' => '2','loc_district_id' => '10','title_en' => 'RANGUNIA','title' => 'রাঙ্গুনীয়া','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '80','loc_division_id' => '2','loc_district_id' => '10','title_en' => 'RAOZAN','title' => 'রাউজান','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '81','loc_division_id' => '2','loc_district_id' => '10','title_en' => 'SANDWIP','title' => 'সন্দ্বীপ','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '82','loc_division_id' => '2','loc_district_id' => '10','title_en' => 'SATKANIA','title' => 'সাতকানীয়া','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '83','loc_division_id' => '2','loc_district_id' => '10','title_en' => 'SITAKUNDA','title' => 'সীতাকুন্ড','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '84','loc_division_id' => '4','loc_district_id' => '36','title_en' => 'ALAMDANGA','title' => 'আলমডাঙ্গা','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '85','loc_division_id' => '4','loc_district_id' => '36','title_en' => 'CHUADANGA SADAR','title' => 'চুয়াডাঙ্গা সদর','is_sadar_upazila' => '1','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '86','loc_division_id' => '4','loc_district_id' => '36','title_en' => 'DAMURHUDA','title' => 'দামুড়হুদা','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '87','loc_division_id' => '4','loc_district_id' => '36','title_en' => 'JIBAN NAGAR','title' => 'জীবন নগর','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '88','loc_division_id' => '2','loc_district_id' => '11','title_en' => 'BARURA','title' => 'বরুড়া','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '89','loc_division_id' => '2','loc_district_id' => '11','title_en' => 'BRAHMAN PARA','title' => 'ব্রাক্ষ্মণ পাড়া','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '90','loc_division_id' => '2','loc_district_id' => '11','title_en' => 'BURICHANG','title' => 'বুড়িচং','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '91','loc_division_id' => '2','loc_district_id' => '11','title_en' => 'CHANDINA','title' => 'চান্দিনা','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '92','loc_division_id' => '2','loc_district_id' => '11','title_en' => 'CHAUDDAGRAM','title' => 'চৌদ্দগ্রাম','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '93','loc_division_id' => '2','loc_district_id' => '11','title_en' => 'COMILLA SADAR DAKSHIN','title' => 'কুমিল্লা সদর দক্ষিণ','is_sadar_upazila' => '1','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '94','loc_division_id' => '2','loc_district_id' => '11','title_en' => 'DAUDKANDI','title' => 'দাউদকান্দি','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '95','loc_division_id' => '2','loc_district_id' => '11','title_en' => 'DEBIDWAR','title' => 'দেবিদ্বার','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '96','loc_division_id' => '2','loc_district_id' => '11','title_en' => 'HOMNA','title' => 'হোমনা','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '97','loc_division_id' => '2','loc_district_id' => '11','title_en' => 'COMILLA ADARSHA SADAR','title' => 'আদর্শ সদর','is_sadar_upazila' => '1','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '98','loc_division_id' => '2','loc_district_id' => '11','title_en' => 'LAKSAM','title' => 'লাকসাম','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '99','loc_division_id' => '2','loc_district_id' => '11','title_en' => 'MANOHARGANJ','title' => 'মনোহরগঞ্জ','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '100','loc_division_id' => '2','loc_district_id' => '11','title_en' => 'MEGHNA','title' => 'মেঘনা','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '101','loc_division_id' => '2','loc_district_id' => '11','title_en' => 'MURADNAGAR','title' => 'মুরাদনগর','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '102','loc_division_id' => '2','loc_district_id' => '11','title_en' => 'NANGALKOT','title' => 'নাঙ্গলকোট','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '103','loc_division_id' => '2','loc_district_id' => '11','title_en' => 'TITAS','title' => 'তিতাস','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '104','loc_division_id' => '2','loc_district_id' => '12','title_en' => 'CHAKARIA','title' => 'চকরিয়া','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '105','loc_division_id' => '2','loc_district_id' => '12','title_en' => 'COX\'S BAZAR SADAR','title' => 'কক্সবাজার সদর','is_sadar_upazila' => '1','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '106','loc_division_id' => '2','loc_district_id' => '12','title_en' => 'KUTUBDIA','title' => 'কুতুবদিয়া','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '107','loc_division_id' => '2','loc_district_id' => '12','title_en' => 'MAHESHKHALI','title' => 'মহেশখালী','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '108','loc_division_id' => '2','loc_district_id' => '12','title_en' => 'PEKUA','title' => 'পেকুয়া','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '109','loc_division_id' => '2','loc_district_id' => '12','title_en' => 'RAMU','title' => 'রামু','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '110','loc_division_id' => '2','loc_district_id' => '12','title_en' => 'TEKNAF','title' => 'টেক্‌নাফ','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '111','loc_division_id' => '2','loc_district_id' => '12','title_en' => 'UKHIA UPAZILA','title' => 'উখিয়া ','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '112','loc_division_id' => '3','loc_district_id' => '18','title_en' => 'TEJGAON UNNAYAN CIRCLE','title' => 'তেজগাঁও উন্নয়ন সার্কেল','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '113','loc_division_id' => '3','loc_district_id' => '18','title_en' => 'DHAMRAI','title' => 'ধামরাই','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '114','loc_division_id' => '3','loc_district_id' => '18','title_en' => 'DOHAR','title' => 'দোহার','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '115','loc_division_id' => '3','loc_district_id' => '18','title_en' => 'KERANIGANJ','title' => 'কেরানীগঞ্জ','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '116','loc_division_id' => '3','loc_district_id' => '18','title_en' => 'NAWABGANJ','title' => 'নবাবগঞ্জ','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '117','loc_division_id' => '3','loc_district_id' => '18','title_en' => 'SAVAR','title' => 'সাভার','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '118','loc_division_id' => '6','loc_district_id' => '53','title_en' => 'BIRAMPUR','title' => 'বিরামপুর','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '119','loc_division_id' => '6','loc_district_id' => '53','title_en' => 'BIRGANJ','title' => 'বীরগঞ্জ','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '120','loc_division_id' => '6','loc_district_id' => '53','title_en' => 'BIRAL','title' => 'বিরল','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '121','loc_division_id' => '6','loc_district_id' => '53','title_en' => 'BOCHAGANJ','title' => 'বোঁচাগঞ্জ','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '122','loc_division_id' => '6','loc_district_id' => '53','title_en' => 'CHIRIRBANDAR','title' => 'চিরিরবন্দর','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '123','loc_division_id' => '6','loc_district_id' => '53','title_en' => 'FULBARI','title' => 'ফুলবাড়ী','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '124','loc_division_id' => '6','loc_district_id' => '53','title_en' => 'GHORAGHAT','title' => 'ঘোড়াঘাট','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '125','loc_division_id' => '6','loc_district_id' => '53','title_en' => 'HAKIMPUR','title' => 'হাকিমপুর','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '126','loc_division_id' => '6','loc_district_id' => '53','title_en' => 'KAHAROLE','title' => 'কাহারোল','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '127','loc_division_id' => '6','loc_district_id' => '53','title_en' => 'KHANSAMA','title' => 'খানসামা','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '128','loc_division_id' => '6','loc_district_id' => '53','title_en' => 'DINAJPUR SADAR','title' => 'দিনাজপুর সদর','is_sadar_upazila' => '1','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '129','loc_division_id' => '6','loc_district_id' => '53','title_en' => 'NAWABGANJ','title' => 'নবাবগঞ্জ','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '130','loc_division_id' => '6','loc_district_id' => '53','title_en' => 'PARBATIPUR','title' => 'পার্বতীপুর','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '131','loc_division_id' => '3','loc_district_id' => '19','title_en' => 'ALFADANGA','title' => 'আলফাডাঙ্গা','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '132','loc_division_id' => '3','loc_district_id' => '19','title_en' => 'BHANGA','title' => 'ভাংগা','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '133','loc_division_id' => '3','loc_district_id' => '19','title_en' => 'BOALMARI','title' => 'বোয়ালমারী','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '134','loc_division_id' => '3','loc_district_id' => '19','title_en' => 'CHAR BHADRASAN','title' => 'চর ভদ্রাসন','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '135','loc_division_id' => '3','loc_district_id' => '19','title_en' => 'FARIDPUR SADAR','title' => 'ফরিদপুর সদর','is_sadar_upazila' => '1','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '136','loc_division_id' => '3','loc_district_id' => '19','title_en' => 'MADHUKHALI','title' => 'মধুখালী','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '137','loc_division_id' => '3','loc_district_id' => '19','title_en' => 'NAGARKANDA','title' => 'নগরকান্দা','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '138','loc_division_id' => '3','loc_district_id' => '19','title_en' => 'SADARPUR','title' => 'সদরপুর','is_sadar_upazila' => '1','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '139','loc_division_id' => '2','loc_district_id' => '13','title_en' => 'CHHAGALNAIYA','title' => 'ছাগলনাইয়া','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '140','loc_division_id' => '2','loc_district_id' => '13','title_en' => 'DAGANBHUIYAN','title' => 'দাগনভূঞাঁ','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '141','loc_division_id' => '2','loc_district_id' => '13','title_en' => 'FENI SADAR','title' => 'ফেনী সদর','is_sadar_upazila' => '1','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '142','loc_division_id' => '2','loc_district_id' => '13','title_en' => 'FULGAZI','title' => 'ফুলগাজী','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '143','loc_division_id' => '2','loc_district_id' => '13','title_en' => 'PARSHURAM','title' => 'পরশুরাম','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '144','loc_division_id' => '2','loc_district_id' => '13','title_en' => 'SONAGAZI','title' => 'সোনাগাজী','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '145','loc_division_id' => '6','loc_district_id' => '54','title_en' => 'FULCHHARI','title' => 'ফুলছড়ি','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '146','loc_division_id' => '6','loc_district_id' => '54','title_en' => 'GAIBANDHA SADAR','title' => 'গাইবান্ধা সদর','is_sadar_upazila' => '1','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '147','loc_division_id' => '6','loc_district_id' => '54','title_en' => 'GOBINDAGANJ','title' => 'গোবিন্দগঞ্জ','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '148','loc_division_id' => '6','loc_district_id' => '54','title_en' => 'PALASHBARI','title' => 'পলাশবাড়ী','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '149','loc_division_id' => '6','loc_district_id' => '54','title_en' => 'SADULLAPUR','title' => 'সাদুল্যাপুর','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '150','loc_division_id' => '6','loc_district_id' => '54','title_en' => 'SAGHATA','title' => 'সাঘাটা','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '151','loc_division_id' => '6','loc_district_id' => '54','title_en' => 'SUNDARGANJ','title' => 'সুন্দরগঞ্জ','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '152','loc_division_id' => '3','loc_district_id' => '20','title_en' => 'GAZIPUR SADAR','title' => 'গাজীপুর সদর','is_sadar_upazila' => '1','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '153','loc_division_id' => '3','loc_district_id' => '20','title_en' => 'KALIAKAIR','title' => 'কালিয়াকৈর','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '154','loc_division_id' => '3','loc_district_id' => '20','title_en' => 'KALIGANJ','title' => 'কালীগঞ্জ','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '155','loc_division_id' => '3','loc_district_id' => '20','title_en' => 'KAPASIA','title' => 'কাপাসিয়া','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '156','loc_division_id' => '3','loc_district_id' => '20','title_en' => 'SREEPUR','title' => 'শ্রীপুর','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '157','loc_division_id' => '3','loc_district_id' => '21','title_en' => 'GOPALGANJ SADAR','title' => 'গোপালগঞ্জ সদর','is_sadar_upazila' => '1','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '158','loc_division_id' => '3','loc_district_id' => '21','title_en' => 'KASHIANI','title' => 'কাশিয়ানী','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '159','loc_division_id' => '3','loc_district_id' => '21','title_en' => 'KOTALIPARA','title' => 'কোটালীপাড়া','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '160','loc_division_id' => '3','loc_district_id' => '21','title_en' => 'MUKSUDPUR','title' => 'মুকসুদপুর','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '161','loc_division_id' => '3','loc_district_id' => '21','title_en' => 'TUNGIPARA','title' => 'টুংগীপাড়া','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '162','loc_division_id' => '7','loc_district_id' => '61','title_en' => 'AJMIRIGANJ','title' => 'আজমিরীগঞ্জ','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '163','loc_division_id' => '7','loc_district_id' => '61','title_en' => 'BAHUBAL','title' => 'বাহুবল','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '164','loc_division_id' => '7','loc_district_id' => '61','title_en' => 'BANIACHONG','title' => 'বানিয়াচং','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '165','loc_division_id' => '7','loc_district_id' => '61','title_en' => 'CHUNARUGHAT','title' => 'চুনারুঘাট','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '166','loc_division_id' => '7','loc_district_id' => '61','title_en' => 'HABIGANJ SADAR','title' => 'হবিগঞ্জ সদর','is_sadar_upazila' => '1','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '167','loc_division_id' => '7','loc_district_id' => '61','title_en' => 'LAKHAI','title' => 'লাখাই','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '168','loc_division_id' => '7','loc_district_id' => '61','title_en' => 'MADHABPUR','title' => 'মাধবপুর','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '169','loc_division_id' => '7','loc_district_id' => '61','title_en' => 'NABIGANJ','title' => 'নবীগঞ্জ','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '170','loc_division_id' => '5','loc_district_id' => '46','title_en' => 'AKKELPUR','title' => 'আক্কেলপুর','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '171','loc_division_id' => '5','loc_district_id' => '46','title_en' => 'JOYPURHAT SADAR','title' => 'জয়পুরহাট সদর','is_sadar_upazila' => '1','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '172','loc_division_id' => '5','loc_district_id' => '46','title_en' => 'KALAI','title' => 'কালাই','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '173','loc_division_id' => '5','loc_district_id' => '46','title_en' => 'KHETLAL','title' => 'ক্ষেতলাল','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '174','loc_division_id' => '5','loc_district_id' => '46','title_en' => 'PANCHBIBI','title' => 'পাঁচবিবি','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '175','loc_division_id' => '8','loc_district_id' => '22','title_en' => 'BAKSHIGANJ','title' => 'বক্‌শীগঞ্জ','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '176','loc_division_id' => '8','loc_district_id' => '22','title_en' => 'DEWANGANJ','title' => 'দেওয়ানগঞ্জ','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '177','loc_division_id' => '8','loc_district_id' => '22','title_en' => 'ISLAMPUR','title' => 'ইসলামপুর','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '178','loc_division_id' => '8','loc_district_id' => '22','title_en' => 'JAMALPUR SADAR','title' => 'জামালপুর সদর','is_sadar_upazila' => '1','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '179','loc_division_id' => '8','loc_district_id' => '22','title_en' => 'MADARGANJ','title' => 'মাদারগঞ্জ','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '180','loc_division_id' => '8','loc_district_id' => '22','title_en' => 'MELANDAHA','title' => 'মেলান্দহ','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '181','loc_division_id' => '8','loc_district_id' => '22','title_en' => 'SARISHABARI ','title' => 'সরিষাবাড়ী','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '182','loc_division_id' => '4','loc_district_id' => '37','title_en' => 'ABHAYNAGAR','title' => 'অভয়নগর','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '183','loc_division_id' => '4','loc_district_id' => '37','title_en' => 'BAGHER PARA','title' => 'বাঘেরপাড়া','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '184','loc_division_id' => '4','loc_district_id' => '37','title_en' => 'CHAUGACHHA','title' => 'চৌগাছা','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '185','loc_division_id' => '4','loc_district_id' => '37','title_en' => 'JHIKARGACHHA','title' => 'ঝিকরগাছা','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '186','loc_division_id' => '4','loc_district_id' => '37','title_en' => 'KESHABPUR','title' => 'কেশবপুর','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '187','loc_division_id' => '4','loc_district_id' => '37','title_en' => 'Jessore Sadar','title' => 'যশোর সদর','is_sadar_upazila' => '1','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '188','loc_division_id' => '4','loc_district_id' => '37','title_en' => 'MANIRAMPUR','title' => 'মনিরামপুর','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '189','loc_division_id' => '4','loc_district_id' => '37','title_en' => 'SHARSHA','title' => 'শার্শা','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '190','loc_division_id' => '1','loc_district_id' => '4','title_en' => 'JHALOKATI SADAR','title' => 'ঝালকাঠী সদর','is_sadar_upazila' => '1','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '191','loc_division_id' => '1','loc_district_id' => '4','title_en' => 'KANTHALIA','title' => 'কাঁঠালিয়া','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '192','loc_division_id' => '1','loc_district_id' => '4','title_en' => 'NALCHITY','title' => 'নলছিটি','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '193','loc_division_id' => '1','loc_district_id' => '4','title_en' => 'RAJAPUR','title' => 'রাজাপুর','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '194','loc_division_id' => '4','loc_district_id' => '38','title_en' => 'HARINAKUNDA','title' => 'হরিণাকুন্ড','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '195','loc_division_id' => '4','loc_district_id' => '38','title_en' => 'JHENAIDAH SADAR','title' => 'ঝিনাইদহ সদর','is_sadar_upazila' => '1','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '196','loc_division_id' => '4','loc_district_id' => '38','title_en' => 'KALIGANJ','title' => 'কালীগঞ্জ','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '197','loc_division_id' => '4','loc_district_id' => '38','title_en' => 'KOTCHANDPUR','title' => 'কোটচাঁদপুর','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '198','loc_division_id' => '4','loc_district_id' => '38','title_en' => 'MAHESHPUR','title' => 'মহেশপুর','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '199','loc_division_id' => '4','loc_district_id' => '38','title_en' => 'SHAILKUPA','title' => 'শৈলকুপা','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '200','loc_division_id' => '2','loc_district_id' => '14','title_en' => 'DIGHINALA','title' => 'দিঘীনালা','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '201','loc_division_id' => '2','loc_district_id' => '14','title_en' => 'KHAGRACHHARI SADAR','title' => 'খাগড়াছড়ি সদর','is_sadar_upazila' => '1','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '202','loc_division_id' => '2','loc_district_id' => '14','title_en' => 'LAKSHMICHHARI','title' => 'লক্ষীছড়ি','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '203','loc_division_id' => '2','loc_district_id' => '14','title_en' => 'MAHALCHHARI','title' => 'মহালছড়ি','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '204','loc_division_id' => '2','loc_district_id' => '14','title_en' => 'MANIKCHHARI','title' => 'মানিকছড়ি','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '205','loc_division_id' => '2','loc_district_id' => '14','title_en' => 'MATIRANGA','title' => 'মাটিরাঙ্গা','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '206','loc_division_id' => '2','loc_district_id' => '14','title_en' => 'PANCHHARI','title' => 'পানছড়ি','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '207','loc_division_id' => '2','loc_district_id' => '14','title_en' => 'RAMGARH','title' => 'রামগড়','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '208','loc_division_id' => '4','loc_district_id' => '39','title_en' => 'BATIAGHATA','title' => 'বটিয়াঘাটা','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '209','loc_division_id' => '4','loc_district_id' => '39','title_en' => 'Dakop','title' => 'দাকোপ','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '210','loc_division_id' => '4','loc_district_id' => '39','title_en' => 'DUMURIA','title' => 'ডুমুরিয়া','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '211','loc_division_id' => '4','loc_district_id' => '39','title_en' => 'DIGHALIA','title' => 'দিঘলিয়া','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '212','loc_division_id' => '4','loc_district_id' => '39','title_en' => 'KOYRA','title' => 'কয়রা','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '213','loc_division_id' => '4','loc_district_id' => '39','title_en' => 'PAIKGACHHA','title' => 'পাইকগাছা','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '214','loc_division_id' => '4','loc_district_id' => '39','title_en' => 'PHULTALA','title' => 'ফুলতলা','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '215','loc_division_id' => '4','loc_district_id' => '39','title_en' => 'RUPSA','title' => 'রূপসা','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '217','loc_division_id' => '4','loc_district_id' => '39','title_en' => 'TEROKHADA','title' => 'তেরখাদা','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '218','loc_division_id' => '3','loc_district_id' => '23','title_en' => 'AUSTAGRAM','title' => 'অষ্টগ্রাম','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '219','loc_division_id' => '3','loc_district_id' => '23','title_en' => 'BAJITPUR','title' => 'বাজিতপুর','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '220','loc_division_id' => '3','loc_district_id' => '23','title_en' => 'BHAIRAB','title' => 'ভৈরব','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '221','loc_division_id' => '3','loc_district_id' => '23','title_en' => 'HOSSAINPUR','title' => 'হোসেনপুর','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '222','loc_division_id' => '3','loc_district_id' => '23','title_en' => 'ITNA','title' => 'ইটনা','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '223','loc_division_id' => '3','loc_district_id' => '23','title_en' => 'KARIMGANJ','title' => 'করিমগঞ্জ','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '224','loc_division_id' => '3','loc_district_id' => '23','title_en' => 'KATIADI','title' => 'কটিয়াদী','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '225','loc_division_id' => '3','loc_district_id' => '23','title_en' => 'KISHOREGANJ SADAR','title' => 'কিশোরগঞ্জ সদর','is_sadar_upazila' => '1','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '226','loc_division_id' => '3','loc_district_id' => '23','title_en' => 'KULIAR CHAR','title' => 'কুলিয়ারচর','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '227','loc_division_id' => '3','loc_district_id' => '23','title_en' => 'MITHAMAIN','title' => 'মিঠামইন','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '228','loc_division_id' => '3','loc_district_id' => '23','title_en' => 'NIKLI','title' => 'নিকলী','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '229','loc_division_id' => '3','loc_district_id' => '23','title_en' => 'PAKUNDIA','title' => 'পাকুন্দিয়া','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '230','loc_division_id' => '3','loc_district_id' => '23','title_en' => 'TARAIL','title' => 'তাড়াইল','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '231','loc_division_id' => '6','loc_district_id' => '55','title_en' => 'BHURUNGAMARI','title' => 'ভুরুঙ্গামারী','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '232','loc_division_id' => '6','loc_district_id' => '55','title_en' => 'CHAR RAJIBPUR','title' => 'রাজীবপুর','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '233','loc_division_id' => '6','loc_district_id' => '55','title_en' => 'CHILMARI','title' => 'চিলমারী','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '234','loc_division_id' => '6','loc_district_id' => '55','title_en' => 'PHULBARI','title' => 'ফুলবাড়ী','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '235','loc_division_id' => '6','loc_district_id' => '55','title_en' => 'KURIGRAM SADAR','title' => 'কুড়িগ্রাম সদর','is_sadar_upazila' => '1','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '236','loc_division_id' => '6','loc_district_id' => '55','title_en' => 'NAGESHWARI','title' => 'নাগেশ্বরী','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '237','loc_division_id' => '6','loc_district_id' => '55','title_en' => 'RAJARHAT','title' => 'রাজারহাট','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '238','loc_division_id' => '6','loc_district_id' => '55','title_en' => 'RAUMARI','title' => 'রৌমারী','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '239','loc_division_id' => '6','loc_district_id' => '55','title_en' => 'ULIPUR','title' => 'উলিপুর','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '240','loc_division_id' => '4','loc_district_id' => '40','title_en' => 'BHERAMARA','title' => 'ভেড়ামারা','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '241','loc_division_id' => '4','loc_district_id' => '40','title_en' => 'DAULATPUR','title' => 'দৌলতপুর','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '242','loc_division_id' => '4','loc_district_id' => '40','title_en' => 'KHOKSA','title' => 'খোক্‌সা','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '243','loc_division_id' => '4','loc_district_id' => '40','title_en' => 'KUMARKHALI','title' => 'কুমারখালী','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '244','loc_division_id' => '4','loc_district_id' => '40','title_en' => 'KUSHTIA SADAR','title' => 'কুষ্টিয়া সদর','is_sadar_upazila' => '1','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '245','loc_division_id' => '4','loc_district_id' => '40','title_en' => 'MIRPUR','title' => 'মিরপুর','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '246','loc_division_id' => '2','loc_district_id' => '15','title_en' => 'KAMALNAGAR','title' => 'কমলনগর','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '247','loc_division_id' => '2','loc_district_id' => '15','title_en' => 'LAKSHMIPUR SADAR','title' => 'লক্ষ্ণীপুর সদর','is_sadar_upazila' => '1','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '248','loc_division_id' => '2','loc_district_id' => '15','title_en' => 'ROYPUR','title' => 'রায়পুর','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '249','loc_division_id' => '2','loc_district_id' => '15','title_en' => 'RAMGANJ','title' => 'রামগঞ্জ','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '250','loc_division_id' => '2','loc_district_id' => '15','title_en' => 'RAMGATI','title' => 'রামগতি','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '251','loc_division_id' => '6','loc_district_id' => '56','title_en' => 'ADITMARI','title' => 'অদিতমারী','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '252','loc_division_id' => '6','loc_district_id' => '56','title_en' => 'HATIBANDHA','title' => 'হাতীবান্ধা','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '253','loc_division_id' => '6','loc_district_id' => '56','title_en' => 'KALIGANJ','title' => 'কালীগঞ্জ','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '254','loc_division_id' => '6','loc_district_id' => '56','title_en' => 'LALMONIRHAT SADAR','title' => 'লালমনিরহাট সদর','is_sadar_upazila' => '1','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '255','loc_division_id' => '6','loc_district_id' => '56','title_en' => 'PATGRAM','title' => 'পাটগ্রাম','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '256','loc_division_id' => '3','loc_district_id' => '24','title_en' => 'KALKINI','title' => 'কালকিনী','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '257','loc_division_id' => '3','loc_district_id' => '24','title_en' => 'MADARIPUR SADAR','title' => 'মাদারিপুর সদর','is_sadar_upazila' => '1','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '258','loc_division_id' => '3','loc_district_id' => '24','title_en' => 'RAJOIR','title' => 'রাজৈর','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '259','loc_division_id' => '3','loc_district_id' => '24','title_en' => 'SHIB CHAR','title' => 'শিবচর','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '260','loc_division_id' => '4','loc_district_id' => '41','title_en' => 'MAGURA SADAR','title' => 'মাগুরা সদর','is_sadar_upazila' => '1','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '261','loc_division_id' => '4','loc_district_id' => '41','title_en' => 'MOHAMMADPUR','title' => 'মহম্মদপুর','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '262','loc_division_id' => '4','loc_district_id' => '41','title_en' => 'SHALIKHA','title' => 'শালিখা','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '263','loc_division_id' => '4','loc_district_id' => '41','title_en' => 'SREEPUR','title' => 'শ্রীপুর','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '264','loc_division_id' => '3','loc_district_id' => '25','title_en' => 'DAULATPUR','title' => 'দৌলতপুর','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '265','loc_division_id' => '3','loc_district_id' => '25','title_en' => 'GHIOR','title' => 'ঘিওর','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '266','loc_division_id' => '3','loc_district_id' => '25','title_en' => 'HARIRAMPUR','title' => 'হরিরামপুর','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '267','loc_division_id' => '3','loc_district_id' => '25','title_en' => 'MANIKGANJ SADAR','title' => 'মানিকগঞ্জ সদর','is_sadar_upazila' => '1','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '268','loc_division_id' => '3','loc_district_id' => '25','title_en' => 'SATURIA','title' => 'সাটুরিয়া','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '269','loc_division_id' => '3','loc_district_id' => '25','title_en' => 'SHIBALAYA','title' => 'শিবালয়','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '270','loc_division_id' => '3','loc_district_id' => '25','title_en' => 'SINGAIR','title' => 'সিংগাইর','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '271','loc_division_id' => '4','loc_district_id' => '42','title_en' => 'GANGNI','title' => 'গাংনী','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '272','loc_division_id' => '4','loc_district_id' => '42','title_en' => 'MUJIB NAGAR','title' => 'মুজিব নগর','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '273','loc_division_id' => '4','loc_district_id' => '42','title_en' => 'MEHERPUR SADAR','title' => 'মেহেরপুর সদর','is_sadar_upazila' => '1','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '274','loc_division_id' => '7','loc_district_id' => '62','title_en' => 'BARLEKHA','title' => 'বড়লেখা','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '275','loc_division_id' => '7','loc_district_id' => '62','title_en' => 'JURI','title' => 'জুড়ী','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '276','loc_division_id' => '7','loc_district_id' => '62','title_en' => 'KAMALGANJ','title' => 'কমলগঞ্জ','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '277','loc_division_id' => '7','loc_district_id' => '62','title_en' => 'KULAURA','title' => 'কুলাউড়া','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '278','loc_division_id' => '7','loc_district_id' => '62','title_en' => 'MAULVIBAZAR SADAR','title' => 'মৌলভীবাজার সদর','is_sadar_upazila' => '1','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '279','loc_division_id' => '7','loc_district_id' => '62','title_en' => 'RAJNAGAR','title' => 'রাজনগর','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '280','loc_division_id' => '7','loc_district_id' => '62','title_en' => 'SREEMANGAL','title' => 'শ্রীমঙ্গল','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '281','loc_division_id' => '3','loc_district_id' => '26','title_en' => 'GAZARIA','title' => 'গজারিয়া','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '282','loc_division_id' => '3','loc_district_id' => '26','title_en' => 'LOHAJANG','title' => 'লৌহজং','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '283','loc_division_id' => '3','loc_district_id' => '26','title_en' => 'MUNSHIGANJ SADAR','title' => 'মুন্সীগঞ্জ সদর','is_sadar_upazila' => '1','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '284','loc_division_id' => '3','loc_district_id' => '26','title_en' => 'SERAJDIKHAN','title' => 'সিরাজদীখান','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '285','loc_division_id' => '3','loc_district_id' => '26','title_en' => 'SREENAGAR','title' => 'শ্রীনগর','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '286','loc_division_id' => '3','loc_district_id' => '26','title_en' => 'TONGIBARI','title' => 'টঙ্গিবাড়ী','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '287','loc_division_id' => '8','loc_district_id' => '27','title_en' => 'BHALUKA','title' => 'ভালুকা','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '288','loc_division_id' => '8','loc_district_id' => '27','title_en' => 'DHOBAURA','title' => 'ধোবাউড়া','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '289','loc_division_id' => '8','loc_district_id' => '27','title_en' => 'FULBARIA','title' => 'ফুলবাড়ীয়া','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '290','loc_division_id' => '8','loc_district_id' => '27','title_en' => 'GAFFARGAON','title' => 'গফরগাঁও','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '291','loc_division_id' => '8','loc_district_id' => '27','title_en' => 'GAURIPUR','title' => 'গৌরীপুর','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '292','loc_division_id' => '8','loc_district_id' => '27','title_en' => 'HALUAGHAT','title' => 'হালূয়াঘাট','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '293','loc_division_id' => '8','loc_district_id' => '27','title_en' => 'ISHWARGANJ','title' => 'ঈশ্বরগঞ্জ','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '294','loc_division_id' => '8','loc_district_id' => '27','title_en' => 'MYMENSINGH SADAR','title' => 'ময়মনসিংহ সদর','is_sadar_upazila' => '1','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '295','loc_division_id' => '8','loc_district_id' => '27','title_en' => 'MUKTAGACHHA','title' => 'মুক্তাগাছা','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '296','loc_division_id' => '8','loc_district_id' => '27','title_en' => 'NANDAIL','title' => 'নান্দাইল','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '297','loc_division_id' => '8','loc_district_id' => '27','title_en' => 'PHULPUR','title' => 'ফুলপুর','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '298','loc_division_id' => '8','loc_district_id' => '27','title_en' => 'TRISHAL','title' => 'ত্রিশাল','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '299','loc_division_id' => '5','loc_district_id' => '47','title_en' => 'ATRAI','title' => 'আত্রাই','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '300','loc_division_id' => '5','loc_district_id' => '47','title_en' => 'BADALGACHHI','title' => 'বাদলগাছী','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '301','loc_division_id' => '5','loc_district_id' => '47','title_en' => 'DHAMOIRHAT','title' => 'ধামইরহাট','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '302','loc_division_id' => '5','loc_district_id' => '47','title_en' => 'MANDA','title' => 'মান্দা','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '303','loc_division_id' => '5','loc_district_id' => '47','title_en' => 'MAHADEBPUR','title' => 'মহাদেবপুর','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '304','loc_division_id' => '5','loc_district_id' => '47','title_en' => 'NAOGAON SADAR','title' => 'নওগাঁ সদর','is_sadar_upazila' => '1','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '305','loc_division_id' => '5','loc_district_id' => '47','title_en' => 'NIAMATPUR','title' => 'নিয়ামতপুর','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '306','loc_division_id' => '5','loc_district_id' => '47','title_en' => 'PATNITALA','title' => 'পত্নীতলা','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '307','loc_division_id' => '5','loc_district_id' => '47','title_en' => 'PORSHA','title' => 'পোরশা','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '308','loc_division_id' => '5','loc_district_id' => '47','title_en' => 'RANINAGAR','title' => 'রাণীনগর','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '309','loc_division_id' => '5','loc_district_id' => '47','title_en' => 'SAPAHAR','title' => 'সাপাহার','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '310','loc_division_id' => '4','loc_district_id' => '43','title_en' => 'KALIA','title' => 'কালিয়া','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '311','loc_division_id' => '4','loc_district_id' => '43','title_en' => 'LOHAGARA','title' => 'লোহাগড়া','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '312','loc_division_id' => '4','loc_district_id' => '43','title_en' => 'NARAIL SADAR','title' => 'নড়াইল সদর','is_sadar_upazila' => '1','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '313','loc_division_id' => '3','loc_district_id' => '28','title_en' => 'ARAIHAZAR','title' => 'আড়াইহাজার','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '314','loc_division_id' => '3','loc_district_id' => '28','title_en' => 'SONARGAON','title' => 'সোনারগাঁ','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '315','loc_division_id' => '3','loc_district_id' => '28','title_en' => 'BANDAR','title' => 'বন্দর','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '316','loc_division_id' => '3','loc_district_id' => '28','title_en' => 'NARAYANGANJ SADAR','title' => 'নারায়নগঞ্জ সদর','is_sadar_upazila' => '1','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '317','loc_division_id' => '3','loc_district_id' => '28','title_en' => 'RUPGANJ','title' => 'রূপগঞ্জ','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '318','loc_division_id' => '3','loc_district_id' => '29','title_en' => 'BELABO','title' => 'বেলাব','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '319','loc_division_id' => '3','loc_district_id' => '29','title_en' => 'MANOHARDI','title' => 'মনোহরদী','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '320','loc_division_id' => '3','loc_district_id' => '29','title_en' => 'NARSINGDI SADAR','title' => 'নরসিংদী সদর','is_sadar_upazila' => '1','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '321','loc_division_id' => '3','loc_district_id' => '29','title_en' => 'PALASH','title' => 'পলাশ','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '322','loc_division_id' => '3','loc_district_id' => '29','title_en' => 'ROYPURA','title' => 'রায়পুরা','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '323','loc_division_id' => '3','loc_district_id' => '29','title_en' => 'SHIBPUR','title' => 'শিবপুর','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '324','loc_division_id' => '5','loc_district_id' => '48','title_en' => 'BAGATIPARA','title' => 'বাগাতীপাড়া','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '325','loc_division_id' => '5','loc_district_id' => '48','title_en' => 'BARAIGRAM','title' => 'বড়াইগ্রাম','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '326','loc_division_id' => '5','loc_district_id' => '48','title_en' => 'GURUDASPUR','title' => 'গুরুদাসপুর','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '327','loc_division_id' => '5','loc_district_id' => '48','title_en' => 'LALPUR','title' => 'লালপুর','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '328','loc_division_id' => '5','loc_district_id' => '48','title_en' => 'NATORE SADAR','title' => 'নাটোর সদর','is_sadar_upazila' => '1','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '329','loc_division_id' => '5','loc_district_id' => '48','title_en' => 'SINGRA','title' => 'সিংড়া','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '330','loc_division_id' => '5','loc_district_id' => '49','title_en' => 'BHOLAHAT','title' => 'ভোলাহাট','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '331','loc_division_id' => '5','loc_district_id' => '49','title_en' => 'GOMASTAPUR','title' => 'গোমস্তাপুর','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '332','loc_division_id' => '5','loc_district_id' => '49','title_en' => 'NACHOLE','title' => 'নাচোল','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '333','loc_division_id' => '5','loc_district_id' => '49','title_en' => 'CHAPAI NABABGANJ SADAR','title' => 'চাঁপাই নবাবগঞ্জ সদর','is_sadar_upazila' => '1','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '334','loc_division_id' => '5','loc_district_id' => '49','title_en' => 'SHIBGANJ','title' => 'শিবগঞ্জ','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '335','loc_division_id' => '8','loc_district_id' => '30','title_en' => 'ATPARA','title' => 'আটপাড়া','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '336','loc_division_id' => '8','loc_district_id' => '30','title_en' => 'BARHATTA','title' => 'বারহাট্টা','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '337','loc_division_id' => '8','loc_district_id' => '30','title_en' => 'DURGAPUR','title' => 'দুর্গাপুর','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '338','loc_division_id' => '8','loc_district_id' => '30','title_en' => 'KHALIAJURI','title' => 'খালিয়াজুরী','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '339','loc_division_id' => '8','loc_district_id' => '30','title_en' => 'KALMAKANDA','title' => 'কলমাকান্দা','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '340','loc_division_id' => '8','loc_district_id' => '30','title_en' => 'KENDUA','title' => 'কেন্দুয়া','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '341','loc_division_id' => '8','loc_district_id' => '30','title_en' => 'MADAN','title' => 'মদন ','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '342','loc_division_id' => '8','loc_district_id' => '30','title_en' => 'MOHANGANJ','title' => 'মোহনগঞ্জ','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '343','loc_division_id' => '8','loc_district_id' => '30','title_en' => 'NETROKONA SADAR','title' => 'নেত্রকোনা সদর','is_sadar_upazila' => '1','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '344','loc_division_id' => '8','loc_district_id' => '30','title_en' => 'PURBADHALA','title' => 'পূর্বধলা','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '345','loc_division_id' => '6','loc_district_id' => '57','title_en' => 'DIMLA UPAZILA','title' => 'ডিম্‌লা','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '346','loc_division_id' => '6','loc_district_id' => '57','title_en' => 'DOMAR UPAZILA','title' => 'ডোমার','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '347','loc_division_id' => '6','loc_district_id' => '57','title_en' => 'JALDHAKA UPAZILA','title' => 'জলঢাকা ','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '348','loc_division_id' => '6','loc_district_id' => '57','title_en' => 'KISHOREGANJ UPAZILA','title' => 'কিশোরগঞ্জ','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '349','loc_division_id' => '6','loc_district_id' => '57','title_en' => 'NILPHAMARI SADAR UPAZ','title' => 'নীলফামারী সদর ','is_sadar_upazila' => '1','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '350','loc_division_id' => '6','loc_district_id' => '57','title_en' => 'SAIDPUR UPAZILA','title' => 'সৈয়দপুর ','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '351','loc_division_id' => '2','loc_district_id' => '16','title_en' => 'BEGUMGANJ','title' => 'বেগমগঞ্জ','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '352','loc_division_id' => '2','loc_district_id' => '16','title_en' => 'CHATKHIL','title' => 'চাট্‌খিল','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '353','loc_division_id' => '2','loc_district_id' => '16','title_en' => 'COMPANIGANJ','title' => 'কোম্পানীগঞ্জ','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '354','loc_division_id' => '2','loc_district_id' => '16','title_en' => 'HATIYA','title' => 'হাতিয়া','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '355','loc_division_id' => '2','loc_district_id' => '16','title_en' => 'KABIRHAT','title' => 'কবিরহাট','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '356','loc_division_id' => '2','loc_district_id' => '16','title_en' => 'SENBAGH','title' => 'সেনবাগ','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '357','loc_division_id' => '2','loc_district_id' => '16','title_en' => 'SONAIMURI','title' => 'সোনাইমুড়ী','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '358','loc_division_id' => '2','loc_district_id' => '16','title_en' => 'SUBARNACHAR','title' => 'সুবর্ণচর','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '359','loc_division_id' => '2','loc_district_id' => '16','title_en' => 'NOAKHALI SADAR','title' => 'নোয়াখালী সদর','is_sadar_upazila' => '1','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '360','loc_division_id' => '5','loc_district_id' => '50','title_en' => 'ATGHARIA','title' => 'আটঘরিয়া','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '361','loc_division_id' => '5','loc_district_id' => '50','title_en' => 'BERA','title' => 'বেড়া','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '362','loc_division_id' => '5','loc_district_id' => '50','title_en' => 'BHANGURA','title' => 'ভাঙ্গুড়া','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '363','loc_division_id' => '5','loc_district_id' => '50','title_en' => 'CHATMOHAR','title' => 'চাট্‌মোহর','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '364','loc_division_id' => '5','loc_district_id' => '50','title_en' => 'FARIDPUR','title' => 'ফরিদপুর','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '365','loc_division_id' => '5','loc_district_id' => '50','title_en' => 'ISHWARDI','title' => 'ঈশ্বরদী','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '366','loc_division_id' => '5','loc_district_id' => '50','title_en' => 'PABNA SADAR','title' => 'পাবনা সদর','is_sadar_upazila' => '1','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '367','loc_division_id' => '5','loc_district_id' => '50','title_en' => 'SANTHIA','title' => 'সাঁথিয়া','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '368','loc_division_id' => '5','loc_district_id' => '50','title_en' => 'SUJANAGAR','title' => 'সুজানগর','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '369','loc_division_id' => '6','loc_district_id' => '58','title_en' => 'ATWARI','title' => 'আটোয়ারী','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '370','loc_division_id' => '6','loc_district_id' => '58','title_en' => 'BODA','title' => 'বোদা','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '371','loc_division_id' => '6','loc_district_id' => '58','title_en' => 'DEBIGANJ','title' => 'দেবীগঞ্জ','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '372','loc_division_id' => '6','loc_district_id' => '58','title_en' => 'PANCHAGARH SADAR','title' => 'পঞ্চগড় সদর','is_sadar_upazila' => '1','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '373','loc_division_id' => '6','loc_district_id' => '58','title_en' => 'TENTULIA','title' => 'তেঁতুলিয়া','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '374','loc_division_id' => '1','loc_district_id' => '5','title_en' => 'BAUPHAL','title' => 'বাউফল','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '375','loc_division_id' => '1','loc_district_id' => '5','title_en' => 'DASHMINA','title' => 'দশ্‌মিনা','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '376','loc_division_id' => '1','loc_district_id' => '5','title_en' => 'DUMKI UPAZILA','title' => 'দুম্‌কী ','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '377','loc_division_id' => '1','loc_district_id' => '5','title_en' => 'GALACHIPA','title' => 'গলাচিপা','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '378','loc_division_id' => '1','loc_district_id' => '5','title_en' => 'KALA PARA','title' => 'কলাপাড়া','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '379','loc_division_id' => '1','loc_district_id' => '5','title_en' => 'MIRZAGANJ UPAZILA','title' => 'মির্জাগঞ্জ','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '380','loc_division_id' => '1','loc_district_id' => '5','title_en' => 'PATUAKHALI SADAR','title' => 'পটুয়াথালী সদর','is_sadar_upazila' => '1','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '381','loc_division_id' => '1','loc_district_id' => '6','title_en' => 'BHANDARIA','title' => 'ভান্ডারিয়া','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '382','loc_division_id' => '1','loc_district_id' => '6','title_en' => 'KAWKHALI','title' => 'কাউখালী','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '383','loc_division_id' => '1','loc_district_id' => '6','title_en' => 'MATHBARIA','title' => 'মঠবাড়িয়া','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '384','loc_division_id' => '1','loc_district_id' => '6','title_en' => 'NAZIRPUR UPAZILA','title' => 'নাজিরপুর','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '385','loc_division_id' => '1','loc_district_id' => '6','title_en' => 'PIROJPUR SADAR','title' => 'পিরোজপুর সদর','is_sadar_upazila' => '1','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '386','loc_division_id' => '1','loc_district_id' => '6','title_en' => 'NESARABAD (SWARUPKATI)','title' => 'নেছারাবাদ','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '387','loc_division_id' => '1','loc_district_id' => '6','title_en' => 'Indurkani','title' => 'ইন্দুরকানী','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '388','loc_division_id' => '5','loc_district_id' => '51','title_en' => 'BAGHA','title' => 'বাঘা','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '389','loc_division_id' => '5','loc_district_id' => '51','title_en' => 'BAGHMARA','title' => 'বাগমারা','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '390','loc_division_id' => '5','loc_district_id' => '51','title_en' => 'CHARGHAT','title' => 'চারঘাট','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '391','loc_division_id' => '5','loc_district_id' => '51','title_en' => 'DURGAPUR','title' => 'দুর্গাপুর','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '392','loc_division_id' => '5','loc_district_id' => '51','title_en' => 'GODAGARI','title' => 'গোদাগাড়ী','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '393','loc_division_id' => '5','loc_district_id' => '51','title_en' => 'MOHANPUR','title' => 'মোহনপুর','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '394','loc_division_id' => '5','loc_district_id' => '51','title_en' => 'PABA','title' => 'পবা','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '395','loc_division_id' => '5','loc_district_id' => '51','title_en' => 'PUTHIA','title' => 'পুঠিয়া','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '396','loc_division_id' => '5','loc_district_id' => '51','title_en' => 'TANORE','title' => 'তানোর','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '397','loc_division_id' => '3','loc_district_id' => '31','title_en' => 'BALIAKANDI','title' => 'বালিয়াকান্দি','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '398','loc_division_id' => '3','loc_district_id' => '31','title_en' => 'GOALANDA','title' => 'গোয়ালন্দ','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '399','loc_division_id' => '3','loc_district_id' => '31','title_en' => 'PANGSHA','title' => 'পাংশা','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '400','loc_division_id' => '3','loc_district_id' => '31','title_en' => 'RAJBARI SADAR','title' => 'রাজবাড়ী সদর','is_sadar_upazila' => '1','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '401','loc_division_id' => '2','loc_district_id' => '17','title_en' => 'BAGHAICHHARI','title' => 'বাঘাইছড়ি','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '402','loc_division_id' => '2','loc_district_id' => '17','title_en' => 'BARKAL UPAZILA','title' => 'বরকল','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '403','loc_division_id' => '2','loc_district_id' => '17','title_en' => 'KAWKHALI (BETBUNIA)','title' => 'কাউখালী','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '404','loc_division_id' => '2','loc_district_id' => '17','title_en' => 'BELAI CHHARI  UPAZI','title' => 'বিলাইছড়ি','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '405','loc_division_id' => '2','loc_district_id' => '17','title_en' => 'KAPTAI  UPAZILA','title' => 'কাপ্তাই','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '406','loc_division_id' => '2','loc_district_id' => '17','title_en' => 'JURAI CHHARI UPAZIL','title' => 'জুরাছড়ি','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '407','loc_division_id' => '2','loc_district_id' => '17','title_en' => 'LANGADU  UPAZILA','title' => 'লংগদু','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '408','loc_division_id' => '2','loc_district_id' => '17','title_en' => 'NANIARCHAR  UPAZILA','title' => 'নানিয়ারচর','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '409','loc_division_id' => '2','loc_district_id' => '17','title_en' => 'RAJASTHALI  UPAZILA','title' => 'রাজস্থলী','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '410','loc_division_id' => '2','loc_district_id' => '17','title_en' => 'RANGAMATI SADAR  ','title' => 'রাঙ্গামাটি সদর','is_sadar_upazila' => '1','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '411','loc_division_id' => '6','loc_district_id' => '59','title_en' => 'BADARGANJ','title' => 'বদরগঞ্জ','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '412','loc_division_id' => '6','loc_district_id' => '59','title_en' => 'GANGACHARA','title' => 'গংগাচড়া','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '413','loc_division_id' => '6','loc_district_id' => '59','title_en' => 'KAUNIA','title' => 'কাউনিয়া','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '414','loc_division_id' => '6','loc_district_id' => '59','title_en' => 'RANGPUR SADAR','title' => 'রংপুর সদর','is_sadar_upazila' => '1','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '415','loc_division_id' => '6','loc_district_id' => '59','title_en' => 'MITHA PUKUR','title' => 'মিঠাপুকুর','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '416','loc_division_id' => '6','loc_district_id' => '59','title_en' => 'PIRGACHHA','title' => 'পীরগাছা','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '417','loc_division_id' => '6','loc_district_id' => '59','title_en' => 'PIRGANJ','title' => 'পীরগঞ্জ','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '418','loc_division_id' => '6','loc_district_id' => '59','title_en' => 'TARAGANJ','title' => 'তারাগঞ্জ','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '419','loc_division_id' => '3','loc_district_id' => '32','title_en' => 'BHEDARGANJ','title' => 'ভেদরগঞ্জ','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '420','loc_division_id' => '3','loc_district_id' => '32','title_en' => 'DAMUDYA','title' => 'ডামুড্যা','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '421','loc_division_id' => '3','loc_district_id' => '32','title_en' => 'GOSAIRHAT','title' => 'গোসাইরহাট','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '422','loc_division_id' => '3','loc_district_id' => '32','title_en' => 'NARIA','title' => 'নড়িয়া','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '423','loc_division_id' => '3','loc_district_id' => '32','title_en' => 'SHARIATPUR SADAR','title' => 'শরিয়তপুর সদর','is_sadar_upazila' => '1','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '424','loc_division_id' => '3','loc_district_id' => '32','title_en' => 'ZANJIRA','title' => 'জাজিরা','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '425','loc_division_id' => '4','loc_district_id' => '44','title_en' => 'ASSASUNI','title' => 'আশাশুনি','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '426','loc_division_id' => '4','loc_district_id' => '44','title_en' => 'DEBHATA','title' => 'দেবহাটা','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '427','loc_division_id' => '4','loc_district_id' => '44','title_en' => 'KALAROA','title' => 'কলারোয়া','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '428','loc_division_id' => '4','loc_district_id' => '44','title_en' => 'KALIGANJ','title' => 'কালীগঞ্জ','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '429','loc_division_id' => '4','loc_district_id' => '44','title_en' => 'SATKHIRA SADAR','title' => 'সাতক্ষীরা সদর','is_sadar_upazila' => '1','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '430','loc_division_id' => '4','loc_district_id' => '44','title_en' => 'SHYAMNAGAR','title' => 'শ্যামনগর','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '431','loc_division_id' => '4','loc_district_id' => '44','title_en' => 'TALA','title' => 'তালা','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '432','loc_division_id' => '5','loc_district_id' => '52','title_en' => 'BELKUCHI','title' => 'বেলকুচি','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '433','loc_division_id' => '5','loc_district_id' => '52','title_en' => 'CHAUHALI','title' => 'চৌহালী','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '434','loc_division_id' => '5','loc_district_id' => '52','title_en' => 'KAMARKHANDA','title' => 'কামারখন্দ','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '435','loc_division_id' => '5','loc_district_id' => '52','title_en' => 'KAZIPUR','title' => 'কাজীপুর','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '436','loc_division_id' => '5','loc_district_id' => '52','title_en' => 'ROYGANJ','title' => 'রায়গঞ্জ','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '437','loc_division_id' => '5','loc_district_id' => '52','title_en' => 'SHAHJADPUR','title' => 'শাহজাদপুর','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '438','loc_division_id' => '5','loc_district_id' => '52','title_en' => 'SIRAJGANJ SADAR','title' => 'সিরাজগঞ্জ সদর','is_sadar_upazila' => '1','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '439','loc_division_id' => '5','loc_district_id' => '52','title_en' => 'TARASH','title' => 'তাড়াশ','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '440','loc_division_id' => '5','loc_district_id' => '52','title_en' => 'ULLAH PARA','title' => 'উল্লাপাড়া','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '441','loc_division_id' => '8','loc_district_id' => '33','title_en' => 'JHENAIGATI','title' => 'ঝিনাইগাতি','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '442','loc_division_id' => '8','loc_district_id' => '33','title_en' => 'NAKLA','title' => 'নকলা','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '443','loc_division_id' => '8','loc_district_id' => '33','title_en' => 'NALITABARI','title' => 'নালিতাবাড়ী','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '444','loc_division_id' => '8','loc_district_id' => '33','title_en' => 'SHERPUR SADAR','title' => 'শেরপুর সদর','is_sadar_upazila' => '1','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '445','loc_division_id' => '8','loc_district_id' => '33','title_en' => 'SREEBARDI','title' => 'শ্রীবরদী','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '446','loc_division_id' => '7','loc_district_id' => '63','title_en' => 'BISHWAMBARPUR','title' => 'বিশ্বম্ভরপুর','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '447','loc_division_id' => '7','loc_district_id' => '63','title_en' => 'CHHATAK','title' => 'ছাতক','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '448','loc_division_id' => '7','loc_district_id' => '63','title_en' => 'DAKSHIN SUNAMGANJ','title' => 'দক্ষিন সুনামগঞ্জ','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '449','loc_division_id' => '7','loc_district_id' => '63','title_en' => 'DERAI','title' => 'দিরাই','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '450','loc_division_id' => '7','loc_district_id' => '63','title_en' => 'DHARAMPASHA','title' => 'ধর্মপাশা','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '451','loc_division_id' => '7','loc_district_id' => '63','title_en' => 'DOWARABAZAR','title' => 'দোয়ারাবাজার','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '452','loc_division_id' => '7','loc_district_id' => '63','title_en' => 'JAGANNATHPUR','title' => 'জগন্নাথপুর','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '453','loc_division_id' => '7','loc_district_id' => '63','title_en' => 'JAMALGANJ','title' => 'জামালগঞ্জ','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '454','loc_division_id' => '7','loc_district_id' => '63','title_en' => 'SULLA','title' => 'শাল্লা','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '455','loc_division_id' => '7','loc_district_id' => '63','title_en' => 'SUNAMGANJ SADAR','title' => 'সুনামগঞ্জ সদর','is_sadar_upazila' => '1','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '456','loc_division_id' => '7','loc_district_id' => '63','title_en' => 'TAHIRPUR','title' => 'তাহিরপুর','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '457','loc_division_id' => '7','loc_district_id' => '64','title_en' => 'BALAGANJ','title' => 'বালাগঞ্জ','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '458','loc_division_id' => '7','loc_district_id' => '64','title_en' => 'BEANI BAZAR','title' => 'বিয়ানীবাজার','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '459','loc_division_id' => '7','loc_district_id' => '64','title_en' => 'BISHWANATH','title' => 'বিশ্বনাথ','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '460','loc_division_id' => '7','loc_district_id' => '64','title_en' => 'COMPANIGANJ','title' => 'কোম্পানীগঞ্জ','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '461','loc_division_id' => '7','loc_district_id' => '64','title_en' => 'DAKSHIN SURMA','title' => 'দক্ষিণ সুরমা','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '462','loc_division_id' => '7','loc_district_id' => '64','title_en' => 'FENCHUGANJ','title' => 'ফেঞ্চুগঞ্জ','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '463','loc_division_id' => '7','loc_district_id' => '64','title_en' => 'GOLAPGANJ','title' => 'গোলাপগঞ্জ','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '464','loc_division_id' => '7','loc_district_id' => '64','title_en' => 'GOWAINGHAT','title' => 'গোয়াইনঘাট','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '465','loc_division_id' => '7','loc_district_id' => '64','title_en' => 'JAINTIAPUR','title' => 'জৈন্তাপুর','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '466','loc_division_id' => '7','loc_district_id' => '64','title_en' => 'KANAIGHAT','title' => 'কানাইঘাট','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '467','loc_division_id' => '7','loc_district_id' => '64','title_en' => 'SYLHET SADAR','title' => 'সিলেট সদর','is_sadar_upazila' => '1','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '468','loc_division_id' => '7','loc_district_id' => '64','title_en' => 'ZAKIGANJ','title' => 'জকিগঞ্জ','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '469','loc_division_id' => '3','loc_district_id' => '34','title_en' => 'BASAIL','title' => 'বাসাইল','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '470','loc_division_id' => '3','loc_district_id' => '34','title_en' => 'BHUAPUR','title' => 'ভূঞাপুর','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '471','loc_division_id' => '3','loc_district_id' => '34','title_en' => 'DELDUAR','title' => 'দেলদোয়ার','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '472','loc_division_id' => '3','loc_district_id' => '34','title_en' => 'DHANBARI','title' => 'ধনবাড়ী','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '473','loc_division_id' => '3','loc_district_id' => '34','title_en' => 'GHATAIL','title' => 'ঘাটাইল','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '474','loc_division_id' => '3','loc_district_id' => '34','title_en' => 'GOPALPUR','title' => 'গোপালপুর','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '475','loc_division_id' => '3','loc_district_id' => '34','title_en' => 'KALIHATI','title' => 'কালিহাতী','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '476','loc_division_id' => '3','loc_district_id' => '34','title_en' => 'MADHUPUR','title' => 'মধুপুর','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '477','loc_division_id' => '3','loc_district_id' => '34','title_en' => 'MIRZAPUR','title' => 'মির্জাপুর','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '478','loc_division_id' => '3','loc_district_id' => '34','title_en' => 'NAGARPUR','title' => 'নাগরপুর','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '479','loc_division_id' => '3','loc_district_id' => '34','title_en' => 'SAKHIPUR','title' => 'সখীপুর','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '480','loc_division_id' => '3','loc_district_id' => '34','title_en' => 'TANGAIL SADAR','title' => 'টাঙ্গাইল সদর','is_sadar_upazila' => '1','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '481','loc_division_id' => '6','loc_district_id' => '60','title_en' => 'BALIADANGI','title' => 'বালিয়াডাংগী','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '482','loc_division_id' => '6','loc_district_id' => '60','title_en' => 'HARIPUR','title' => 'হরিপুর','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '483','loc_division_id' => '6','loc_district_id' => '60','title_en' => 'PIRGANJ','title' => 'পীরগঞ্জ','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '484','loc_division_id' => '6','loc_district_id' => '60','title_en' => 'RANISANKAIL','title' => 'রানীশংকৈল','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '485','loc_division_id' => '6','loc_district_id' => '60','title_en' => 'THAKURGAON SADAR','title' => 'ঠাকুরগাঁও সদর','is_sadar_upazila' => '1','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '486','loc_division_id' => '3','loc_district_id' => '19','title_en' => 'SALTHA','title' => 'সালথা','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '490','loc_division_id' => '5','loc_district_id' => '48','title_en' => 'Noldanga','title' => 'নলডাঙ্গা','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '491','loc_division_id' => '7','loc_district_id' => '64','title_en' => 'Osmani Nagar','title' => 'ওসমানী নগর','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '493','loc_division_id' => '8','loc_district_id' => '27','title_en' => 'Tarakanda','title' => 'তারাকান্দা','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '495','loc_division_id' => '2','loc_district_id' => '10','title_en' => 'KARNAFULI','title' => 'কর্ণফুলী','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '496','loc_division_id' => '7','loc_district_id' => '61','title_en' => 'Shayestaganj','title' => 'শায়েস্তাগঞ্জ','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '497','loc_division_id' => '1','loc_district_id' => '1','title_en' => 'TALTALI','title' => 'তালতলী','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '498','loc_division_id' => '2','loc_district_id' => '14','title_en' => 'Guimara','title' => 'গুইমারা','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL),
            array('id' => '499','loc_division_id' => '2','loc_district_id' => '11','title_en' => 'Lalmai','title' => 'লালমাই','is_sadar_upazila' => '0','bbs_code' => NULL,'deleted_at' => NULL)
        ));



        Schema::enableForeignKeyConstraints();

    }
}
